AWSTemplateFormatVersion: "2010-09-09"
Description: Remote-Brilliance-Tiffin

Parameters:
  ApiName:
    Type: String
    Default: Remote-Brilliance
  AppSyncRole:
    Type: String
    Default: arn:aws:iam::762379509945:role/service-role/appsync-ds-ddb-dlathc-RemoteBrillianceTabl
  AppSyncPushToCloudWatchLogs:
    Type: String
    Default: arn:aws:iam::762379509945:role/AppSyncPushToCloudWatchLogs
  RBS3Bucket:
    Type: String
    Default: remote-brilliance-cloud
  enableDynamoDBTableEncryption:
    Type: String
    Description: This is used to specify if the DynamoDB tables should be encrypted.
    Default: true
    AllowedValues: [true, false]
  dynamoDBTableBillingMode:
    Type: String
    Description: This is used to configure the billing mode on the DynamoDB tables.
    Default: PAY_PER_REQUEST

Resources:
  SNSRole:
    Type: AWS::IAM::Role
    Description: "An IAM Role to allow Cognito to send SNS messages"
    Properties:
      RoleName: !Sub ${ApiName}-cognito-sns-role
      ManagedPolicyArns:
        - Ref: CognitoSNSPolicy
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - cognito-idp.amazonaws.com
    DependsOn:
      - CognitoSNSPolicy

  #Cognito Related Resources
  CognitoSNSPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Managed policy to allow Amazon Cognito to access SNS
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sns:publish
            Resource: "*"

  UserPool:
    Type: "AWS::Cognito::UserPool"
    Description: "A Cognito user pool for authenticating users"
    Properties:
      UserPoolName: !Sub ${ApiName}-user-pool
      AutoVerifiedAttributes:
        - phone_number
      MfaConfiguration: "ON"
      SmsConfiguration:
        ExternalId: !Sub ${ApiName}-external
        SnsCallerArn: !GetAtt SNSRole.Arn
      Schema:
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
        - Name: phone_number
          AttributeDataType: String
          Mutable: false
          Required: true

  UserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Description: "App Client used by AWS AppSync"
    Properties:
      ClientName: !Sub ${ApiName}-appsync-client
      GenerateSecret: false
      UserPoolId: !Ref UserPool

  # Data Source Resources
  UserProfile:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      SSESpecification:
        SSEEnabled: { "Ref": "enableDynamoDBTableEncryption" }

  RemoteBrillianceAppSync:
    Type: AWS::AppSync::GraphQLApi
    Description: "Remote Brilliance Endpoints"
    Properties:
      Name: !Sub ${ApiName}
      AuthenticationType: "AMAZON_COGNITO_USER_POOLS"
      UserPoolConfig:
        UserPoolId: !Ref UserPoolClient
        AwsRegion: !Sub ${AWS::Region}
        DefaultAction: "ALLOW"
      LogConfig:
        CloudWatchLogsRoleArn: !Sub ${AppSyncPushToCloudWatchLogs}
        ExcludeVerboseContent: False
        FieldLogLevel: ALL

  RemoteBrillianceSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt RemoteBrillianceAppSync.ApiId
      DefinitionS3Location: !Sub "s3://${RBS3Bucket}/schema.graphql"
  UserProfileDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      Name: "UserProfileDataSource"
      ApiId: !GetAtt RemoteBrillianceAppSync.ApiId
      DynamoDBConfig:
        TableName: !Ref UserProfile
        AwsRegion: !Ref "AWS::Region"
      ServiceRoleArn: !Sub ${AppSyncRole}
      Type: AMAZON_DYNAMODB

Outputs:
  GraphQLApiEndpoint:
    Description: The URL to the GraphQL Endpoint
    Value: !GetAtt RemoteBrillianceAppSync.GraphQLUrl
  GraphQLApiId:
    Description: The API ID of the GraphQL API
    Value: !GetAtt RemoteBrillianceAppSync.ApiId
  CognitoUserPoolId:
    Description: The Pool ID of the Cognito User Pool
    Value: !Ref UserPool
  CognitoUserPoolClientId:
    Description: The Client ID for AWS AppSync Auth
    Value: !Ref UserPoolClient
  UserProfileTableName:
    Description: The name of the DynamoDB Table
    Value: !Ref UserProfile
#   # AppSyncLogGroup:
#   #   Type: AWS::Logs::LogGroup
#   #   Properties:
#   #     LogGroupName: !Sub "/aws/appsync/apis/${RemoteBrillianceAppSync.ApiId}"
#   #     RetentionInDays: 90

#   # AppSyncApiKey:
#   #   Type: AWS::AppSync::ApiKey
#   #   Properties:
#   #     Description: "Basic OpenWeatherMap API Key"
#   #     Expires: 1640995200 # Jan 24 2022
#   #     ApiId: !GetAtt RemoteBrillianceAppSync.ApiId
